language: objective-c
osx_image: xcode8
install:
- gem install xcpretty
script:
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project Limitless.xcodeproj -scheme Limitless -destination 'platform=iOS Simulator,name=iPhone 6s' build test | xcpretty
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e523819b2ed9235ca1ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
